### ISSUE TITLE
Add Spray Action README Support

### ISSUE THREAD

**Issue by Zamanry** [ShutdownRepo/pywhisker#10]
Thank you for this great Python port! The README has not been updated to include the `--action spray`. I swore that the tool supported it, but couldn't find it until I read the PRs: #6

This addition would help others realize faster that this tool supports this great feature like the C# ShadowSpray tool.

**Comment by ShutdownRepo** [comment]
Agreed, if you would be able to make a pull request on this it'd be awesome as it's not in the priorities right now.
Would you be able/willing?

**Comment by Zamanry** [comment]
Yep, I’ll get on it within the next week!
