### ISSUE TITLE
Unable to write shadow credentials across domains (and forests if that is supported)

### ISSUE THREAD

**Issue by jsdhasfedssad** [ShutdownRepo/pywhisker#13]
Hi,

Thank you for this tool.

During testing of the new cross-domain shadow credential writing I encountered an issue. As you can see in the pictures, `adlab.local\adlab_shadow1` has full control of `child.adlab.local\child_domainuser1` but still the writing of shadow credentials fails due to insufficient rights. I have no issues writing shadow credentials within a domain.

The trust involved is a parent-child trust where `adlab.local` is the parent domain and `child.adlab.local` is the child domain.

![pywhisker2](https://github.com/ShutdownRepo/pywhisker/assets/97032878/394e2505-a82b-474d-997a-96d9616b8d50)

![pywhisker1](https://github.com/ShutdownRepo/pywhisker/assets/97032878/8ea76ed8-9630-4686-84c0-909e951faa51)

**Comment by jsdhasfedssad** [comment]
I actually did try targeting the child domain DC and tried checking access rights using dacledit.py before posting. Here is a screenshot of the first but I had issues using dacledit.py so I have no screenshot of that at the moment. I will try again. 

![pywhisker3](https://github.com/ShutdownRepo/pywhisker/assets/97032878/06fc1bd5-5208-48ec-8f50-08bbb3bcc646)

**Comment by ShutdownRepo** [comment]
Alright, then I think it's most likely your user doesn't really have the permission to do shadow creds on the target for some reason.

**Comment by jsdhasfedssad** [comment]
You were right. Strangely enough `adlab_shadow1` did not have write access to `child_domainuser1` despite the settings in ADUC...

Authenticating using `adlab.local\administrator` works.
