### ISSUE TITLE
Feature request: pipx support

### ISSUE THREAD

**Issue by fsacer** [ShutdownRepo/pywhisker#16]
It would be awesome to have pipx support for this useful package so it's even easier to deal with python virtual envs. To make it work the `setup.py` or `pyproject.toml` file is needed as per docs https://pipx.pypa.io/latest/how-pipx-works/.

**Comment by ShutdownRepo** [comment]
Agreed, I would very much like to have pipx support
However, I have very few time at the moment, do you mind creating a PR I could review & merge on this matter?

**Comment by rb-x** [comment]
Hello @ShutdownRepo, here's the PR for pipx support #20

**Comment by ShutdownRepo** [comment]
Fixed in #20
