### ISSUE TITLE
Is -k working?

### ISSUE THREAD

**Issue by jsdhasfeds** [ShutdownRepo/pywhisker#2]
Hi. Thank you very much for your time writing this tool! 

I can successfully add shadow credentials when authenticating using a plaintext password but when I try the same using Kerberos authentication on the same machine in the same "session" it fails with "invalid server address". I have tested all kind of variations of the parameters such as "-d [domain]" and "--dc-ip [DC IP]" in various locations of the command but I always get the same error. Note that I have no issues using for example Impacket's secretsdump script with Kerberos in the same environment.

I also noted that you have not used the "-k" parameter in any of your examples here so I cannot check my command against an example.

**Comment by TahiTi** [comment]
Hey @jsdhasfeds, I just created a [PR](https://github.com/ShutdownRepo/pywhisker/pull/3) solving the issue, feel free to try it out :)

**Comment by ShutdownRepo** [comment]
Should be fixed in #3 and #4, closing the issue, feel free to open it again if needed :wink:
