### ISSUE TITLE
This is another project of yours(describeTicket.py). I use it to obtain the session key~How can I solve it and obtain the session key!!!

### ISSUE THREAD

**Issue by flagxxx** [ShutdownRepo/pywhisker#8]
![image](https://user-images.githubusercontent.com/84010022/204598069-c72aab29-43f7-4b81-8c4c-2d68b426bc30.png)
https://pbs.twimg.com/media/FiV43yLWQAQdvnV.jpg

**Comment by flagxxx** [comment]
https://pbs.twimg.com/media/FiV43yLWQAQdvnV.jpg

**Comment by ShutdownRepo** [comment]
Hey there
1. you should open the issue either on Impacket's official repo or one one of my forks (https://github.com/ThePorgs/impacket, https://github.com/ShutdownRepo/impacket), but I don't think it belongs here
2. I see you're using python2, I advise you to use python3 instead.
3. You need to make sure you're using the latest version of describeTicket.

Please try the following
1. download Exegol's fork of Impacket (a fork I maintain for Exegol) `git pull https://github.com/ThePorgs/impacket`
2. install pipx and use it to install impacket in a dedicate venv, making sure you won't have dependencies conflicts : `pip3 install pipx && pipx install /path/to/impacket`
3. try again the describe ticket `describeTicket.py "whatever.ccache"`

Closing the ticket here. Feel free to open it again elsewhere if needed.
I hope you'll manage to make it work.
