### ISSUE TITLE
unsupported hash type md4

### ISSUE THREAD

**Issue by ivanov21** [ShutdownRepo/pywhisker#9]
I get "unsupported hash type md4" when trying to add new value:

![whisk](https://github.com/ShutdownRepo/pywhisker/assets/38586468/684412d9-ca58-4310-9fd1-fb3c468ff535)

**Comment by ShutdownRepo** [comment]
Can you run again in debug (`-vv`) please ?

**Comment by ShutdownRepo** [comment]
Closing. @ivanov21 please open again if you're able to show the debug logs

**Comment by null-hyp0thesis** [comment]
This is an issue with Hashlib deprecating MD4 after a certain point.

# Resolution:
Add this to your /etc/ssl/openssl.cnf to 're-enable' md4 to hashlib

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1


# Ref: 
https://stackoverflow.com/questions/69938570/md4-hashlib-support-in-python-3-8

Debug:
```
  File "/usr/lib/python3.12/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type MD4
```
